### ISSUE TITLE
Only support Manual Mode(仅支持手动模式)

### ISSUE THREAD

**Issue by LiuSky** [ronghaopger/EasyPull#1]
像这种业务场景我不是很理解，基本上这个方法没人会去用。

**Comment by ronghaopger** [comment]
@LiuSky 你好，你说的是这个手动下拉刷新吗？这个是最常用的场景啊。可能你指错了。
那我说说这个上拉，上拉加载分为两种Mode，手动上拉的场景是有的，有些时候你希望只有用户手动触发再去加载更多，而不是滑动到底部后就自动去加载。 自动上拉当然就是当滑动到页面底端时自动去加载。
这些场景都是有的。

**Comment by LiuSky** [comment]
我的意思是： 没必要分手动或者被动，应该两者合为一体，你爱手动，你就手动，爱被动那就自己触发默个事件，我个人是这样子理解的。特别上下拉刷新。不知道还是不是有理解错误
发自我的 iPhone
