### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by Gilbertat** [ronghaopger/EasyPull#3]
这是我的app截图 [Screenshot](http://7xrrm2.com1.z0.glb.clouddn.com/Simulator%20Screen%20Shot%202016%E5%B9%B43%E6%9C%8811%E6%97%A5%2017.31.16.png)
起始位置似乎不太对
只添加了这一行代码
`tableView.easy_addDropPull({
            self.httpRequest()
})
`

**Comment by ronghaopger** [comment]
@Gilbertat  
self.navigationBar.translucent = false
设置navigationBar为不透明
tabBar同理

**Comment by Gilbertat** [comment]
问题解决感谢
