### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by Gilbertat** [ronghaopger/EasyPull#5]
当下拉手动模式，上拉自动模式配合使用，滑动过快会出现以下结果
[问题截图](http://7xrrm2.com1.z0.glb.clouddn.com/thumb_IMG_1291_1024.jpg)

**Comment by ronghaopger** [comment]
@Gilbertat  解决了，你拉下来看看。
以后可以自己试着解决，欢迎pull request   :)
